In [1]:
import tensorflow as tf

In [2]:
x=tf.random.normal(shape=(2,2))
y=tf.random.normal(shape=(2,2))

$ f(x,y) = \sqrt{(x^2 +y^2)}$

$ \nabla f(x,y) = \frac{\partial f}{\partial x} \hat{\imath} + \frac{\partial f}{\partial y} \hat{\imath}$

In [5]:
with tf.GradientTape() as tape:
    tape.watch(x)##I want to calcuate gradient wrt x
    f=tf.sqrt(tf.square(x) + tf.square(y))
    df_dx=tape.gradient(f,x)
    print(df_dx)

tf.Tensor(
[[ 0.9717826   0.50861585]
 [-0.09010362 -0.2214592 ]], shape=(2, 2), dtype=float32)


In [7]:
with tf.GradientTape() as tape:
    tape.watch(y)### I want to calculate gradient of y wrt y
    f=tf.sqrt(tf.square(x)+tf.square(y))
    df_dy=tape.gradient(f,y)
    print(df_dy)

tf.Tensor(
[[ 0.2358785  -0.8609936 ]
 [-0.9959324  -0.97516966]], shape=(2, 2), dtype=float32)


In [8]:
with tf.GradientTape() as tape:
    tape.watch(x)
    tape.watch(y)
    f=tf.sqrt(tf.square(x)+tf.square(y))
    df_dx,df_dy=tape.gradient(f,[x,y])
    print(df_dx)
    print(df_dy)

tf.Tensor(
[[ 0.9717826   0.50861585]
 [-0.09010362 -0.2214592 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0.2358785  -0.8609936 ]
 [-0.9959324  -0.97516966]], shape=(2, 2), dtype=float32)
