In [1]:
import tensorflow as tf

In [2]:
const_mat=tf.constant([[1,2],[4,5]])

In [3]:
const_mat

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5]])>

In [4]:
const_mat.shape

TensorShape([2, 2])

In [5]:
const_mat.dtype

tf.int32

In [6]:
const_mat[0][0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [7]:
const_mat[0][0]=32

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

# Commonly used method

In [8]:
tf.ones(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [9]:
-tf.ones(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-1., -1., -1.],
       [-1., -1., -1.]], dtype=float32)>

In [10]:
6*tf.ones(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[6., 6., 6.],
       [6., 6., 6.]], dtype=float32)>

In [11]:
tf.zeros(shape=(2,4))

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [12]:
# if want to use placeholder
tf.zeros(shape=(2,5))

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

# Add Operation

In [13]:
const1=tf.constant([[1,2,3],[4,5,6]])
const2=tf.constant([[3,4,5],[6,5,4]])
const1+const2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 4,  6,  8],
       [10, 10, 10]])>

In [14]:
tf.add(const1, const2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 4,  6,  8],
       [10, 10, 10]])>

# Define Random constant

In [16]:
tf.random.normal(shape=(2,2), mean=0, stddev=1.0)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.7632131 , -0.05170982],
       [ 0.75062376,  0.44512075]], dtype=float32)>

In [17]:
tf.random.uniform(shape=(2,2), minval=0,maxval=20)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 7.5903726, 12.793877 ],
       [ 1.2498069, 10.140471 ]], dtype=float32)>

# Variables

In [18]:
var1=tf.Variable([[1,2,3],[4,5,6]])

In [19]:
var2=tf.Variable(43)

In [20]:
var2.assign(56)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=56>

In [21]:
var2

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=56>

# Reshaping operation