In [1]:
import tensorflow as tf

In [2]:
const_mat=tf.constant([[1,2],[4,5]])

In [3]:
const_mat

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5]])>

In [4]:
const_mat.shape

TensorShape([2, 2])

In [5]:
const_mat.dtype

tf.int32

In [6]:
const_mat[0][0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [7]:
const_mat[0][0]=32

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

# Commonly used method

In [8]:
tf.ones(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [9]:
-tf.ones(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-1., -1., -1.],
       [-1., -1., -1.]], dtype=float32)>

In [10]:
6*tf.ones(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[6., 6., 6.],
       [6., 6., 6.]], dtype=float32)>

In [11]:
tf.zeros(shape=(2,4))

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [12]:
# if want to use placeholder
tf.zeros(shape=(2,5))

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

# Add Operation

In [13]:
const1=tf.constant([[1,2,3],[4,5,6]])
const2=tf.constant([[3,4,5],[6,5,4]])
const1+const2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 4,  6,  8],
       [10, 10, 10]])>

In [14]:
tf.add(const1, const2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 4,  6,  8],
       [10, 10, 10]])>

# Define Random constant

In [16]:
tf.random.normal(shape=(2,2), mean=0, stddev=1.0)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.7632131 , -0.05170982],
       [ 0.75062376,  0.44512075]], dtype=float32)>

In [17]:
tf.random.uniform(shape=(2,2), minval=0,maxval=20)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 7.5903726, 12.793877 ],
       [ 1.2498069, 10.140471 ]], dtype=float32)>

# Variables

In [18]:
var1=tf.Variable([[1,2,3],[4,5,6]])

In [19]:
var2=tf.Variable(43)

In [20]:
var2.assign(56)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=56>

In [21]:
var2

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=56>

var2=33

In [22]:
var2=33

In [23]:
type(var2)

int

In [24]:
var1.assign([[22,2,3],[4,5,6]])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[22,  2,  3],
       [ 4,  5,  6]])>

In [25]:
var1.assign([[22,2,3],[4,5,6],[6,7,8]])

ValueError: Cannot assign value to variable ' Variable:0': Shape mismatch.The variable shape (2, 3), and the assigned value shape (3, 3) are incompatible.

In [26]:
var1[1,1].assign(56)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[22,  2,  3],
       [ 4, 56,  6]])>

## reshape operation

In [27]:
tensor=tf.Variable([[22,2,3],[4,5,6]])
tensor.shape

TensorShape([2, 3])

In [30]:
tf.reshape(tensor,[3,2])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[22,  2],
       [ 3,  4],
       [ 5,  6]])>

In [31]:
tf.reshape(tensor,[1,6])

<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[22,  2,  3,  4,  5,  6]])>

In [32]:
tf.reshape(tensor,[6,1])

<tf.Tensor: shape=(6, 1), dtype=int32, numpy=
array([[22],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6]])>

## Other Mathematical operation

In [33]:
tf.square(var1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 484,    4,    9],
       [  16, 3136,   36]])>

# BroadCasting in TF

In [34]:
tensor

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[22,  2,  3],
       [ 4,  5,  6]])>

In [35]:
scaler=4

In [36]:
tensor*scaler

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[88,  8, 12],
       [16, 20, 24]])>

In [37]:
scaler +tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[26,  6,  7],
       [ 8,  9, 10]])>

In [38]:
scaler-tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[-18,   2,   1],
       [  0,  -1,  -2]])>

## Matrix Multiplication

In [43]:
mat_u=tf.constant([[3,4,5]])
mat_v=tf.constant([[5,4,3]])

In [42]:
mat_u.shape

TensorShape([1, 3])

In [48]:
#Rele column of matrix of A=row of Matrix b if you multiply
tf.matmul(mat_u,tf.transpose(mat_v))

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[46]])>

In [49]:
tf.matmul(tf.transpose(mat_u), mat_v)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[15, 12,  9],
       [20, 16, 12],
       [25, 20, 15]])>

In [50]:
mat_u@tf.transpose(mat_v)

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[46]])>

In [52]:
#element wise ultiplication
# shape should be same both of the matrix
mat_u*mat_v

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[15, 16, 15]])>

In [53]:
mat_u.dtype

tf.int32

In [54]:
# can be use reduce the size of the model to save the space in the memory allocation
tf.cast(mat_u,tf.int16)

<tf.Tensor: shape=(1, 3), dtype=int16, numpy=array([[3, 4, 5]], dtype=int16)>